[package]
name = "grovedb"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.merkletree]
version = "0.21.0"

[dependencies.blake3]
version = "1.0.0"